name: Lua CI

on:
  push:
    paths-ignore:
      - '**.md'
      - '.github/workflows/**'
      - '.vscode/**'
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Lua/LuaJIT
      uses: leafo/gh-actions-lua@v6
