name: Lua CI

on:
  push:
    paths-ignore:
      - '**.md'
      - '.github/workflows/**'
      - '.vscode/**'
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:    
    - name: Lua Docker Image
      uses: mileschou/lua-action@master
      with:
        args: lua main.lua
