name: Lua CI

on:
  push:
    paths-ignore:
      - '**.md'
      - '.github/workflows/**'
      - '.vscode/**'
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Lua/LuaJIT
      uses: leafo/gh-actions-lua@v6
    
    - name: Install LuaRocks
      uses: leafo/gh-actions-luarocks@v2
    
    - name: Lua Action
      uses: mileschou/lua-action@master
      with:
        args: lua -v
    
    - name: Build
      run: |
        luarocks install busted
        luarocks install moonscript
        luarocks make
#        luarocks install https://github.com/bawdeveloppement/love2d-ecs
    
    - name: Test
      run: |
        busted -o utfTerminal
